stages:
  - checkout
  - build
  - test
  - coverage

variables:
  DOCKER_IMAGE: 'gradle-docker-example'

checkout:
  stage: checkout
  script:
    - git clone https://github.com/Chaithu12345678/Gradle3.git

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE .

test:
  stage: test
  script:
    - ./gradlew test

coverage:
  stage: coverage
  script:
    - ./gradlew jacocoTestReport

cleanup:
  stage: cleanup
  script:
    - docker rmi $DOCKER_IMAGE || true
  when: always

success_message:
  stage: cleanup
  script:
    - echo 'Build and tests completed successfully!'
  when: on_success

failure_message:
  stage: cleanup
  script:
    - echo 'Build or tests failed!'
  when: on_failure
